fix: update rocks for 1.8
canonical/kubeflow-rocks pull request #56
Opened 2023-10-11 16:25 UTC by i-chvets

# Description

Required updates for ROCK for 1.8

Summary of changes:
- Updated service command to use env vars.
- Added comment on usage of env vars.
- Updated sanity tests to use env vars.

2023-10-26 13:36 UTC, SamirPS requested changes

2023-10-26 13:36 UTC, SamirPS commented on jupyter-pytorch-cuda-full/tests/test_access.py
> +    time.sleep(5)
can you add some logic like wait until the webpage is ready?

2023-10-26 13:36 UTC, SamirPS commented on jupyter-pytorch-full/tests/test_access.py
> +    time.sleep(5)
same

2023-10-26 13:36 UTC, SamirPS commented on jupyter-scipy/tests/test_access.py
> +    time.sleep(5)
same

2023-10-26 13:37 UTC, SamirPS commented
Do you also test the HOME variable?

2025-01-20 15:13 UTC, orfeas-k commented
Not relevant anymore

2025-01-20 15:13 UTC, closed without merging